/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'dark-blue': '#0A2342',
        'electric-blue': '#2364AA',
        'aqua': '#73BFB8',
        'night-blue': '#051630',
        'deep-blue': '#153154',
        'royal-blue': '#1E4D8C',
        'sky-blue': '#3A7FC8',
        'light-blue': '#5A9BD9',
        'pastel-blue': '#A8D0F0',
        'light-gray': '#F5F7FA',
        'medium-gray': '#E2E8F0',
        'dark-gray': '#2D3748',
        'success': '#10B981',
        'warning': '#FBBF24',
        'error': '#EF4444',
        'info': '#3B82F6',
        // Legacy colors for backward compatibility
        primary: {
          DEFAULT: '#2364AA',
          light: '#5A9BD9',
          dark: '#0A2342',
        },
        secondary: '#73BFB8',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        accent: ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'h1': '3rem',
        'h2': '2.25rem',
        'h3': '1.875rem',
        'h4': '1.5rem',
        'subtitle-1': '1.25rem',
        'subtitle-2': '1.125rem',
        'body': '1rem',
        'body-sm': '0.875rem',
        'small': '0.75rem',
      },
      fontWeight: {
        light: 300,
        regular: 400,
        medium: 500,
        semibold: 600,
        bold: 700,
      },
      borderRadius: {
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
      },
      boxShadow: {
        'sm': '0 1px 3px rgba(0, 0, 0, 0.1)',
        'md': '0 4px 6px rgba(0, 0, 0, 0.1)',
        'lg': '0 10px 15px rgba(0, 0, 0, 0.1)',
        'xl': '0 20px 25px rgba(0, 0, 0, 0.1)',
        'soft': '0 4px 20px rgba(0, 0, 0, 0.08)',
        'hover': '0 10px 40px rgba(0, 0, 0, 0.1)',
      },
      backgroundImage: {
        'gradient-primary': 'linear-gradient(135deg, #0A2342 0%, #2364AA 100%)',
        'gradient-accent': 'linear-gradient(135deg, #2364AA 0%, #73BFB8 100%)',
        'gradient-light': 'linear-gradient(135deg, #F5F7FA 0%, #E2E8F0 100%)',
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
      animation: {
        'bounce-slow': 'bounce 3s infinite',
        'pulse-slow': 'pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'float': 'float 6s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-20px)' },
        }
      },
      transitionDuration: {
        'fast': '150ms',
        'normal': '300ms',
        'slow': '500ms',
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '5': '1.25rem',
        '6': '1.5rem',
        '8': '2rem',
        '10': '2.5rem',
        '12': '3rem',
        '16': '4rem',
        '20': '5rem',
        '24': '6rem',
        '32': '8rem',
        '40': '10rem',
        '48': '12rem',
        '56': '14rem',
        '64': '16rem',
      },
    },
  },
  variants: {
    extend: {
      opacity: ['disabled'],
      backgroundColor: ['disabled', 'active'],
      textColor: ['disabled', 'active'],
      borderColor: ['disabled', 'active', 'focus-visible'],
      ringColor: ['focus-visible'],
      ringWidth: ['focus-visible'],
    },
  },
  plugins: [],
}
